version: "3.8"

services:
  adasdb:
    container_name: adasdb
    image: postgres:alpine
    env_file: .env
    volumes:
      - adas-postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - adayasong

  adas:
    build:
      context: ./
      dockerfile: infra/images/local/adas.Dockerfile
    volumes:
      - .:/home/app
    networks:
      - adayasong
    env_file: .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`a_day_a_song.localhost`)

  reverse-proxy:
    image: traefik:v2.4
    container_name: adas-reverse-proxy
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080"
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=adayasong
      - traefik.http.routers.reverse-proxy.rule=Host(`traefik.localhost`)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - adayasong

volumes:
  adas-postgres-data: null
networks:
  adayasong:
    name: aday_a_song
